### PR TITLE
optimize some achievement forcn

### PR DESCRIPTION
**Pull request by MsLGXC**

### CODE REVIEW

**Comment by Klowby** [comment]
Some achievements have stories behind them, or references to songs/films/characters.

eg: Troll toll (at line 152)
https://youtu.be/cZiEAdpX3_o
And the icon of this achievement is from the troll mentioned in the link above.

Just a reminder, nothing much :)

**Comment by MsLGXC** [comment]
> Some achievements have stories behind them, or references to songs/films/characters.
> 
> eg: Troll toll (at line 152) https://youtu.be/cZiEAdpX3_o And the icon of this achievement is from the troll mentioned in the link above.
> 
> Just a reminder, nothing much :)

yeah, i noticed that some of their content used puns or quoted other works of art
your translation has been done very well,there is not much to improve
but I really can't find a reliable conclusion about the quotation of "troll toll"
i think it just refers to the behavior of "imposing tolls", which is called "abominable trolls"
so according to the context of this map and its sub, i translated it as "The death knell that hastens your death"
Of course, it can also be understood as "zombies impose your toll", but it seems a little superficial. If that ture, I will withdraw this one

**Comment by MsLGXC** [comment]
> Some achievements have stories behind them, or references to songs/films/characters.
> 
> eg: Troll toll (at line 152) https://youtu.be/cZiEAdpX3_o And the icon of this achievement is from the troll mentioned in the link above.
> 
> Just a reminder, nothing much :)

similarly, in article 128: AC/DC - T.N.T
I also found that you quoted this song as the name of the achievement, but i think it seems that you have lost the significance of localizing the achievement by using this song as a translation. on the one hand, it is because people know little about it, so it is not popular and difficult to understand. second, it may conflict with the overall translation style

**Comment by MsLGXC** [comment]
> Some achievements have stories behind them, or references to songs/films/characters.
> 
> eg: Troll toll (at line 152) https://youtu.be/cZiEAdpX3_o And the icon of this achievement is from the troll mentioned in the link above.
> 
> Just a reminder, nothing much :)

changes to this line have been deleted. anything else to pay attention？

**Comment by MsLGXC** [comment]
> Some achievements have stories behind them, or references to songs/films/characters.
> 
> eg: Troll toll (at line 152) https://youtu.be/cZiEAdpX3_o And the icon of this achievement is from the troll mentioned in the link above.
> 
> Just a reminder, nothing much :)

changes to this line have been deleted. anything else to pay attention？

**Comment by Klowby** [comment]
Look good to me :)
I fully understand your consideration, and hope you don't mind discussing different point of views.

**Comment by felis-catus** [comment]
Merging as changes are approved by Klowby, thank you!

**Pull request merged**
