### PR TITLE
Update SChinese localization

### PR DESCRIPTION
**Pull request by Klowby**
I assume this new 'Select Mutators' feature
`
"NMRiH_Select_Mutators" "Select Mutators"
`
is associated with
`
"ChallengeReject_OutsideVScript"	"Custom VScript was run."
`.

So I translated "Select Mutators" more like "Select Custom VScripts".
Hope that I didn't misunderstand the new feature.

TY!

### CODE REVIEW

**Comment by AtheistNMRiH** [comment]
no, mutators and vscript aren't the same

**Comment by Klowby** [comment]
Alright, seems that I got it wrong.
I saw that pic about the mutators feature in discord. Those items inside make me feel like.... similar to sourcemod plugins.
But I guess mutators can do much more things to game levels.
I'd better just translate words straightforward.
Now the meaning of the strings is like “Choose Modifiers”. (Since I can't express the word 'Mutators' way more better...)

Thanks for the reply!

**Comment by AtheistNMRiH** [comment]
yeah, I have translated it the same way for russian 😃

**Comment by felis-catus** [comment]
> Choose Modifiers

Looks good! I was going to suggest this, "mutator" is a fancy word for changing something, mainly derived from programming terminology: 
https://en.wiktionary.org/wiki/mutator

I would also translate it to "modifier" equivalent in my native language.

Merged, thank you!

**Pull request merged**
