### PR TITLE
Schinese news update

### PR DESCRIPTION
**Pull request by MsLGXC**
I have some doubts about some of the content, but I am considering whether it is necessary to ask questions

### CODE REVIEW

**Comment by Klowby** [comment]
You did good bro, and players can understand what news post is about after translation imo. From ur translation I can tell u are an experienced player, so dont worry about the understanding in those contents. Also feel free to ask questions.

For me the hard part are "Fixes" and "Changes for mappers and modders".  Here are some of my humble tips.
````
- Check github issues from issue number in "Fixes" for more detail
(https://github.com/nmrih/source-game/issues/)
- Check Valve Developer Community to understand some use of terms
(https://developer.valvesoftware.com/wiki/Main_Page)
- Keep some key words stay original if can't find accurate translation.
(Cuz I dont have much experience using hammer, coding scripts, plugins etc..)
````

Thats pretty much all I got, also u could check PlazeHorta's translation, he translated better than me and helped me correct some problems before (Hope he doesnt mind I mentioned him here).

Well, we are just community translators, and we dont have many ppl, so dont really expect outselves can translate 100% correct. Just do what we can do is enough :D

**Comment by MsLGXC** [comment]
> You did good bro, and players can understand what news post is about after translation imo. From ur translation I can tell u are an experienced player, so dont worry about the understanding in those contents. Also feel free to ask questions.
> 
> For me the hard part are "Fixes" and "Changes for mappers and modders". Here are some of my humble tips.
> 
> ```
> - Check github issues from issue number in "Fixes" for more detail
> (https://github.com/nmrih/source-game/issues/)
> - Check Valve Developer Community to understand some use of terms
> (https://developer.valvesoftware.com/wiki/Main_Page)
> - Keep some key words stay original if can't find accurate translation.
> (Cuz I dont have much experience using hammer, coding scripts, plugins etc..)
> ```
> 
> Thats pretty much all I got, also u could check PlazeHorta's translation, he translated better than me and helped me correct some problems before (Hope he doesnt mind I mentioned him here).
> 
> Well, we are just community translators, and we dont have many ppl, so dont really expect ourselves can translate 100% correct. Just do what we can do is enough :D

The first question about "clips"
Based on my experience in other games, "clips" sometimes seem to mean different things, sometimes models, sometimes animations, and sometimes textures. So I think it should be translated according to its original meaning, but there is no suitable translation for this word in this context. So I translated it as "models" based on your previous translation
If it is only modified to "tweak", it will make the content too short
Also note that in tchinese, it is kept as "VPhysics clips"
just want to confirm if there is a better way to express, even though the creators and people may not actually care about what specific modifications have been made

**Comment by MsLGXC** [comment]
second: overlay is overlay or item esp?

> You did good bro, and players can understand what news post is about after translation imo. From ur translation I can tell u are an experienced player, so dont worry about the understanding in those contents. Also feel free to ask questions.
> 
> For me the hard part are "Fixes" and "Changes for mappers and modders". Here are some of my humble tips.
> 
> ```
> - Check github issues from issue number in "Fixes" for more detail
> (https://github.com/nmrih/source-game/issues/)
> - Check Valve Developer Community to understand some use of terms
> (https://developer.valvesoftware.com/wiki/Main_Page)
> - Keep some key words stay original if can't find accurate translation.
> (Cuz I dont have much experience using hammer, coding scripts, plugins etc..)
> ```
> 
> Thats pretty much all I got, also u could check PlazeHorta's translation, he translated better than me and helped me correct some problems before (Hope he doesnt mind I mentioned him here).
> 
> Well, we are just community translators, and we dont have many ppl, so dont really expect ourselves can translate 100% correct. Just do what we can do is enough :D

sec. "overlay"is overlay or item esp?

**Comment by MsLGXC** [comment]
> You did good bro, and players can understand what news post is about after translation imo. From ur translation I can tell u are an experienced player, so dont worry about the understanding in those contents. Also feel free to ask questions.
> 
> For me the hard part are "Fixes" and "Changes for mappers and modders". Here are some of my humble tips.
> 
> ```
> - Check github issues from issue number in "Fixes" for more detail
> (https://github.com/nmrih/source-game/issues/)
> - Check Valve Developer Community to understand some use of terms
> (https://developer.valvesoftware.com/wiki/Main_Page)
> - Keep some key words stay original if can't find accurate translation.
> (Cuz I dont have much experience using hammer, coding scripts, plugins etc..)
> ```
> 
> Thats pretty much all I got, also u could check PlazeHorta's translation, he translated better than me and helped me correct some problems before (Hope he doesnt mind I mentioned him here).
> 
> Well, we are just community translators, and we dont have many ppl, so dont really expect ourselves can translate 100% correct. Just do what we can do is enough :D

3.“level" is survival map wave?if so we can use a better translation

**Comment by MsLGXC** [comment]
> You did good bro, and players can understand what news post is about after translation imo. From ur translation I can tell u are an experienced player, so dont worry about the understanding in those contents. Also feel free to ask questions.
> 
> For me the hard part are "Fixes" and "Changes for mappers and modders". Here are some of my humble tips.
> 
> ```
> - Check github issues from issue number in "Fixes" for more detail
> (https://github.com/nmrih/source-game/issues/)
> - Check Valve Developer Community to understand some use of terms
> (https://developer.valvesoftware.com/wiki/Main_Page)
> - Keep some key words stay original if can't find accurate translation.
> (Cuz I dont have much experience using hammer, coding scripts, plugins etc..)
> ```
> 
> Thats pretty much all I got, also u could check PlazeHorta's translation, he translated better than me and helped me correct some problems before (Hope he doesnt mind I mentioned him here).
> 
> Well, we are just community translators, and we dont have many ppl, so dont really expect ourselves can translate 100% correct. Just do what we can do is enough :D

4.what is "overlord"?

**Comment by Klowby** [comment]
Well Its like most of them are terms from hammer editor or even source engine, and I dont have much experience using it. So my answears might not be correct.

1 - Tweak clips 
In my knowledge, it might be some invincible textures or might be a reference to the clipping tool (can search them in Valve Developer Community). So whether its gonna restrain player movement or cut brushes to different shapes, I assume them as a modification to ingame models that we can see. Such as walls, fence or something. If we really need to translate it seriously, maybe it can be "some modifications to brushes", and followed the SChinese Valve Developer Community translation.

2 - Overlay
Also used in hammer editor, I think overlay in the news post means adding overlays on some surface of brushes. Similar to u sprayed a picture on a wall. The esp u said is also a kind of meaning of the word overlay, but its not used in here I guess.

3 - Level
I guess level is just another saying of map.. the level transition in the news post is like u can go to next map without loading a new progress bar? Its just like playing hl2 when it comes level change.

4 - Overlord
They are some entities that nmrih use and related to zombie spawn controlling. So I assume they are just like some spawners in minecraft.

Or we just keep those words stay english when we can't find any suitable translations. Also asking questions in offical discord can be a good way to solve problems.

**Comment by MsLGXC** [comment]
> Well Its like most of them are terms from hammer editor or even source engine, and I dont have much experience using it. So my answears might not be correct.
> 
> 1 - Tweak clips In my knowledge, it might be some invincible textures or might be a reference to the clipping tool (can search them in Valve Developer Community). So whether its gonna restrain player movement or cut brushes to different shapes, I assume them as a modification to ingame models that we can see. Such as walls, fence or something. If we really need to translate it seriously, maybe it can be "some modifications to brushes", and followed the SChinese Valve Developer Community translation.
> 
> 2 - Overlay Also used in hammer editor, I think overlay in the news post means adding overlays on some surface of brushes. Similar to u sprayed a picture on a wall. The esp u said is also a kind of meaning of the word overlay, but its not used in here I guess.
> 
> 3 - Level I guess level is just another saying of map.. the level transition in the news post is like u can go to next map without loading a new progress bar? Its just like playing hl2 when it comes level change.
> 
> 4 - Overlord They are some entities that nmrih use and related to zombie spawn controlling. So I assume they are just like some spawners in minecraft.
> 
> Or we just keep those words stay english when we can't find any suitable translations. Also asking questions in offical discord can be a good way to solve problems.

thank you explain

**Comment by AtheistNMRiH** [comment]
"tweak clips" - you are right, "clips" are invisible brushes which prevent players/npc movement, no reference to clipping tool here, and basically they were modified/added/deleted

**Comment by MsLGXC** [comment]
> Well Its like most of them are terms from hammer editor or even source engine, and I dont have much experience using it. So my answears might not be correct.
> 
> 1 - Tweak clips In my knowledge, it might be some invincible textures or might be a reference to the clipping tool (can search them in Valve Developer Community). So whether its gonna restrain player movement or cut brushes to different shapes, I assume them as a modification to ingame models that we can see. Such as walls, fence or something. If we really need to translate it seriously, maybe it can be "some modifications to brushes", and followed the SChinese Valve Developer Community translation.
> 
> 2 - Overlay Also used in hammer editor, I think overlay in the news post means adding overlays on some surface of brushes. Similar to u sprayed a picture on a wall. The esp u said is also a kind of meaning of the word overlay, but its not used in here I guess.
> 
> 3 - Level I guess level is just another saying of map.. the level transition in the news post is like u can go to next map without loading a new progress bar? Its just like playing hl2 when it comes level change.
> 
> 4 - Overlord They are some entities that nmrih use and related to zombie spawn controlling. So I assume they are just like some spawners in minecraft.
> 
> Or we just keep those words stay english when we can't find any suitable translations. Also asking questions in offical discord can be a good way to solve problems.



> Well Its like most of them are terms from hammer editor or even source engine, and I dont have much experience using it. So my answears might not be correct.
> 
> 1 - Tweak clips In my knowledge, it might be some invincible textures or might be a reference to the clipping tool (can search them in Valve Developer Community). So whether its gonna restrain player movement or cut brushes to different shapes, I assume them as a modification to ingame models that we can see. Such as walls, fence or something. If we really need to translate it seriously, maybe it can be "some modifications to brushes", and followed the SChinese Valve Developer Community translation.
> 
> 2 - Overlay Also used in hammer editor, I think overlay in the news post means adding overlays on some surface of brushes. Similar to u sprayed a picture on a wall. The esp u said is also a kind of meaning of the word overlay, but its not used in here I guess.
> 
> 3 - Level I guess level is just another saying of map.. the level transition in the news post is like u can go to next map without loading a new progress bar? Its just like playing hl2 when it comes level change.
> 
> 4 - Overlord They are some entities that nmrih use and related to zombie spawn controlling. So I assume they are just like some spawners in minecraft.
> 
> Or we just keep those words stay english when we can't find any suitable translations. Also asking questions in offical discord can be a good way to solve problems.

It seems that the "level" may be related to the newly added non survival map defense，Many Chinese people are discussing that, saying it will allow waves and kill counts similar to survival maps to appear in the obj map.
But strangely, if this is a new feature, there is no need to call it a fix because it has never been released before. But others believe that maybe related to "level" or survival in obj map

**Comment by MsLGXC** [comment]
> > Well Its like most of them are terms from hammer editor or even source engine, and I dont have much experience using it. So my answears might not be correct.
> > 1 - Tweak clips In my knowledge, it might be some invincible textures or might be a reference to the clipping tool (can search them in Valve Developer Community). So whether its gonna restrain player movement or cut brushes to different shapes, I assume them as a modification to ingame models that we can see. Such as walls, fence or something. If we really need to translate it seriously, maybe it can be "some modifications to brushes", and followed the SChinese Valve Developer Community translation.
> > 2 - Overlay Also used in hammer editor, I think overlay in the news post means adding overlays on some surface of brushes. Similar to u sprayed a picture on a wall. The esp u said is also a kind of meaning of the word overlay, but its not used in here I guess.
> > 3 - Level I guess level is just another saying of map.. the level transition in the news post is like u can go to next map without loading a new progress bar? Its just like playing hl2 when it comes level change.
> > 4 - Overlord They are some entities that nmrih use and related to zombie spawn controlling. So I assume they are just like some spawners in minecraft.
> > Or we just keep those words stay english when we can't find any suitable translations. Also asking questions in offical discord can be a good way to solve problems.
> 
> > Well Its like most of them are terms from hammer editor or even source engine, and I dont have much experience using it. So my answears might not be correct.
> > 1 - Tweak clips In my knowledge, it might be some invincible textures or might be a reference to the clipping tool (can search them in Valve Developer Community). So whether its gonna restrain player movement or cut brushes to different shapes, I assume them as a modification to ingame models that we can see. Such as walls, fence or something. If we really need to translate it seriously, maybe it can be "some modifications to brushes", and followed the SChinese Valve Developer Community translation.
> > 2 - Overlay Also used in hammer editor, I think overlay in the news post means adding overlays on some surface of brushes. Similar to u sprayed a picture on a wall. The esp u said is also a kind of meaning of the word overlay, but its not used in here I guess.
> > 3 - Level I guess level is just another saying of map.. the level transition in the news post is like u can go to next map without loading a new progress bar? Its just like playing hl2 when it comes level change.
> > 4 - Overlord They are some entities that nmrih use and related to zombie spawn controlling. So I assume they are just like some spawners in minecraft.
> > Or we just keep those words stay english when we can't find any suitable translations. Also asking questions in offical discord can be a good way to solve problems.
> 
> It seems that the "level" may be related to the newly added non survival map defense，Many Chinese people are discussing that, saying it will allow waves and kill counts similar to survival maps to appear in the obj map. But strangely, if this is a new feature, there is no need to call it a fix because it has never been released before. But others believe that maybe related to "level" or survival in obj map

Another theory is that multiple round map or two maps can be connected in some way. Maps marked as the same series will not reset their health status and items during level transitions 
Similar to archive inheritance to experience a coherent plot
To be honest, they confused me. I'm not a developer, lol
All I can do now is keep nothing modified

**Comment by MsLGXC** [comment]
Perhaps you don't mind helping me find answers on Discord?
For some reason, I haven't logged into it for a year, and there are some bad things

**Pull request merged**
