### PR TITLE
Fix MidwestVoice.EngineerStart duration, etc

### PR DESCRIPTION
**Pull request by Plazehorta**

### CODE REVIEW

**Comment by Klowby** [comment]
Hey plaze, did u test SChinese closed caption before changing duration time?
Cuz some caption codes are different from your version, and I already made them synced with my translation.
I don't mind these new changes, since they also match their original sounds.
But if you didn't notice yet, I want to let you know :) 

In SChinese colsed caption file:
- I extended duration time to make some sentences with more time to read.
(Since they may contain some illegible words, and maybe these sentences are just too long.)
- I want to make segments appear together in a short time.
(Old caption codes made segments appear one by one in just one line, one ended, then another appeard. How about we made them more readable with multiple lines, and in a short time.)
(eg: we have A, B, and C three segments. And i try to express my idea by using a picture.)
sum
- Break sentence into more segments.
(I noticed that some segments are still too long for nmrih to display.)
(eg: in map nmo_quatantine. Some segments may not display right after their sound begins. And break them into more little pieces can solve the problem.)

Above are just some of my thoughts about closed caption, sorry for taking your time to read.
And I gotta thank you for using caption codes to make closed caption become more useful.
Such an amazing idea!

**Comment by Plazehorta** [comment]
I noticed there are differences on your part, but I didn't pay too much attention on how it works and how it looks. The strings I fixed there are extending even over the next phrase, so I believe, I could have overlooked something to be honest.

Although overlapping durations of the string and the next is generally a good idea, I hesitated doing that for fear of there could be issue with captions flooding with sfx and player inputs at first. But then, since I have been playing with how the captions are currently on my end, I see how the flooding issue is there anyway with or without the overlapping.

Some other note; there's a phrase "private Jones from the 42nd", in JunctionVoice.02, it is refering to the 42nd Infantry Division.

**Comment by Klowby** [comment]
Totally understand, player inputs are also an issue.
No matters how closed captions are gonna change, at least they are already translated.
And player also have their point of view when translation released.

Thanks for the kind reminder. I noticed that phrase a couple days ago by reading your translation.
It was my fault.
And it should comes from the movie 28 Days Later, if I didn't search wrong.
I am gonna pull another request later for that phrase. If you dont mind, I will follow your translation.
Ty!

**Comment by felis-catus** [comment]
Merged, thank you!

**Pull request merged**
